### PR TITLE
[early WIP] Python protocol support 

### PR DESCRIPTION
**Pull request by pvh**
After a couple hours of learning SWIG and messing with typemaps, I think I'm starting to see what's happening here. This is able to grab some bytes and pass them (maybe?) to the GameState but then it either crashes or fails to render and reports None. I suspect I likely still have an error with how I'm passing in the bytearray, but maybe you can learn from my mistakes.

### CODE REVIEW

**Comment by pvh** [comment]
Oh also (out) doesn't work, it's just a copy-paste of (in)

**Comment by pvh** [comment]
Next on my wish-list is to figure out the `print` stuff, since without it it's a pain to debug anything here and my solution so far is to stub out the print implementation you provided. Suggestions welcome!

**Comment by Gronis** [comment]
Yea the print stuff is really nice if it works. I've made some changes to it but I dont know if it works on the Pi. I think I might be able to push something that works this weekend with parsing data sent over the network. Let's hope for the best :)

**Comment by pvh** [comment]
Awesome! I figure we can get it running on a PC and worry about the Pi later (compilation cycles are so slow there.) Does that mean you've pushed up a new patch? If so I'll grab it and play later tonight.

**Comment by Gronis** [comment]
I'm closing this merge request because these changes here are no longer needed after other changes. Feel free to reopen if you disagree.

**Comment by pvh** [comment]
👍

**Pull request closed without merging**
